name: CD:-Cloudformation

on:
  workflow_call:
  push:
    branches:
      - uat

jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependency
        run: yarn install --frozen-lockfile
      - name: Linting
        run: yarn eslint
